### ISSUE TITLE
Interesting addon, should work on ACF5

### ISSUE THREAD

**Issue by virgo79** [micc83/acf-fonticonpicker#1]
Hi mic, 
I found your addon very interesting: icons are shown very well.
Should be updated for ACF5 and should be added the ability to shown the dropdown filter by categories.
Awesome work!
Thank you very much.

**Comment by micc83** [comment]
Hi @virgo79, at the moment i've no time to support ACF5 nor to update to new fontIconPicker version. Hopefully someone will take it from here...

**Comment by micc83** [comment]
Added ACF5 support in #2
