### ISSUE TITLE
Plugin not compatible with ACF PRO 5.5.14 - stopped working and took site down

### ISSUE THREAD

**Issue by earthjibber** [micc83/acf-fonticonpicker#10]
Not sure what happened but it seems that your plugin is no longer compatible with the main ACF pro plugin. I have disabled/enabled all plugins and my site goes down when i have ACF pro enabled and then enabled acf-fonticonpicker, while all other plugins are disabled.

Any ideas, or will there be an update of your plugin anytime soon?

Now that I have your plugin deactivated, all of the icons I added to my site are no longer showing.

thanks

**Comment by tmconnect** [comment]
What does it mean "my site goes down"? Did you get an error message? Are there any messages in the console?

It would be helpful, if you will provide the plugin author and the people who want to help with some information...

**Comment by earthjibber** [comment]
Sorry, there aren't any errors in my error log related to your plugin and when having both ACF pro and your plugin enabled my site will not load, I get a timeout error, 503 Bad Gateway. I have the site on a dedicated server hosted with Rackspace and I have control over everything. I tried changing the php versions, I tried disabling all plugins and enabling them all one at a time. When I have your plugin and ACF pro enabled that is when I have issues. I went through 3 hours of troubleshooting this.

It has been working fine for over 3 months and unfortunately I'm now having problems. I have tried a lot of different things, including asking Rackspace support to help me try and figure out what the cause of the problem is and they have come to the same result that when having ACF pro and your plugin enabled the site will not load.

If you need any information let me know.

**Comment by tmconnect** [comment]
I'm not the plugin developer - I only did read your message and wondering, why there is no more information about the errors.

I hope the developer could help...

**Comment by micc83** [comment]
Hello @earthjibber,
I've just tried acf-fonticonpicker with WordPress 4.8 and ACF Pro 5.5.14 without any kind of issue. Without more informations or some error log I'm sorry but there's nothing I can do.

Cheers,
Alex

**Comment by earthjibber** [comment]
I figured it out micc83, sorry, it was a theme issue. Plugin works great been using it on multiple sites now. Thanks
