### ISSUE TITLE
Multiple options inside the repeater fields

### ISSUE THREAD

**Issue by azam1** [micc83/acf-fonticonpicker#14]
WhenI add the icon field inside a repeater it shows multiple icon selectors

<img width="504" alt="screen shot 2018-05-01 at 10 57 47 pm" src="https://user-images.githubusercontent.com/7868435/39473633-23180978-4d93-11e8-814c-7f9591b44166.png">

**Comment by micc83** [comment]
Hello @azam1, I'm not following the project anymore. If you'd like you can send a PR to fix the issue and I'll check it out as soon as I have some spare time.
