### ISSUE TITLE
Plugin does not save data if you use it in the new ACF Block feature

### ISSUE THREAD

**Issue by DuffmanCC** [micc83/acf-fonticonpicker#15]
ACF  v5.8.0-beta2

I'm creating Gutenberg blocks with the new version of ACF which is still in beta and the icon picker don't save any data.

It works fine if you use it as a normal field but not with blocks.

**Comment by bfiessinger** [comment]
same issue. Except you update another field too.

**Comment by bfiessinger** [comment]
@DuffmanCC update the jquery.fonticonpicker.min.js to v2.0.0 from https://raw.githubusercontent.com/micc83/fontIconPicker/master/jquery.fonticonpicker.min.js and it will work.

**Comment by micc83** [comment]
Thank you for the support @dabasti.

**Comment by bfiessinger** [comment]
you're welcome. Could you update the code so that the issue disappears?
