### ISSUE TITLE
Add Icomoon font

### ISSUE THREAD

**Issue by Bobolions** [micc83/acf-fonticonpicker#5]
Hi,

I noticed the JSON file of Fontello is edited and matches the PHP code. But how can I add Icomoon icons?
Any help would be much appreciated.

Best regards

**Comment by micc83** [comment]
Hi @Bobolions unfortunately the first version of fontIconPicker doesn't support Icomoon fonts natively. However IcoMoon is supported by fontIconPicker v2 http://codeb.it/fonticonpicker/. You can try making ACF fontIconPicker work with fontIconPicker v2 if you wish...

Sorry I couldn't help you more.

Cheers,
Alex
