### ISSUE TITLE
Composer Installation - Upload to plugin repository or packagist

### ISSUE THREAD

**Issue by patrickgalbraith** [micc83/acf-fonticonpicker#6]
Would it be possible to add this to the Wordpress plugin repository (https://wordpress.org/plugins/).

Or alternatively you could just add a `composer.json` file see this for an example https://github.com/Rarst/wps/blob/master/composer.json. You may need to move the contents of the `acf-fonticonpicker` directory to the top level.

The reason I need this is that it is a pain to manage dependencies like this manually.

**Comment by micc83** [comment]
The reason I didn't add it to WP plugins repo is that it's a pain in the a*\* working with svn.  About adding the composer.json file you can create a PR. I've never used composer to handle WP plugins and no time to figure it out. 

Cheers, Alex

**Comment by patrickgalbraith** [comment]
@micc83 see pull request #7

**Comment by micc83** [comment]
Done, try it out and let me know. 

Thank you, Alex

**Comment by patrickgalbraith** [comment]
@micc83

Hey Alex. 
Thanks for accepting the PR. Just one thing can you submit the package to Packagist (https://packagist.org/packages/submit). I can't do it since it's under your namespace. You only have to submit it once and then it will auto-update from then on. You can login with your Github account so it should only take a sec.
Thanks heaps, Patrick

**Comment by micc83** [comment]
Done. Could you please update the readme file and add some doc on how to install the plugin through composer (or whatever, I'm not sure how packagist works with WP)? 

Thank you, Alex

**Comment by micc83** [comment]
Merged #8, thank you for the contribution.
