### ISSUE TITLE
Plugin path

### ISSUE THREAD

**Issue by simoneprodesign** [micc83/acf-fonticonpicker#9]
Hi,

I've installed this in my custom theme but I don't wanna to use it as a plugin but I wanna to use it within theme.

The problem is this:

Including it in the "functions.php" however the dependencies ask me from the "wp-content / plugin" folder.

I installed the "git clone" trait plugin inside a folder contained in the theme.

Can you help me understand?

**Comment by micc83** [comment]
Hello Simone,

I'm not sure to understand what is your problem here. If you want to use this library in your theme just download the whole thing in a new `acf-fonticonpicker` folder within your theme path and include it with:
```php
include_once('acf-fonticonpicker/acf-fonticonpicker.php');
```

Cheers,
Alex

**Comment by simoneprodesign** [comment]
Sorry, my english is very bad.

I've include it with 
`include_once('acf-fonticonpicker/acf-fonticonpicker.php');`
but the file doesnt'load (js, css etc).

**Comment by micc83** [comment]
Try to add the following to your functions.php file, before the plugin include:

```php
add_filter( 'acf/acf_field_fonticonpicker/settings', function ($settings) {
    var_dump($settings);
    return $settings;
} );
```

Check the output of the dump. If the paths are not the right one you can fix them accordingly to your needs.

**Comment by simoneprodesign** [comment]
```
array(5) {
  ["dir"]=>
  string(214) "wp-content/themes/themename/_/_inc/_plugin/acf-fonticonpicker/"
  ["path"]=>
  string(214) "wp-content/themes/themename/bios-prevention/_/_inc/_plugin/acf-fonticonpicker/"
  ["config"]=>
  string(231) "wp-content/themes/themename/_/_inc/_plugin/acf-fonticonpicker/icons/config.json"
  ["icons"]=>
  string(236) "wp-content/themes/themename/_/_inc/_plugin/acf-fonticonpicker/icons/css/fontello.css"
  ["version"]=>
  string(5) "1.0.0"
}
```

**Comment by micc83** [comment]
Well, if those are not the intended path you can fix them through the filter above. Something like:

```php
add_filter( 'acf/acf_field_fonticonpicker/settings', function ($settings) {
    $settings['dir'] = 'custom-dir';
    $settings['path'] = 'custom-path';
    // etc...
    return $settings;
} );
```
If you're not sure how to valorize those fields install the library as a standard wp plugin and check the dump. 

Cheers

**Comment by simoneprodesign** [comment]
OK, 
I've resolved this, but I can not load Icomoon custom icons.

```
add_filter( 'acf/acf_field_fonticonpicker/settings', function ($settings) {
$settings['dir'] = get_stylesheet_directory_uri() . '/_/_inc/_plugin/acf-fonticonpicker/';
$settings['path'] = get_stylesheet_directory_uri() . '/_/_inc/_plugin/acf-fonticonpicker/';
$settings['icons'] = get_stylesheet_directory_uri() . '/_/_css/icon.min.css';
$settings['config'] = get_stylesheet_directory_uri() . '/_/_font/medical-icons.json';
return $settings;
```

But the selector doesn't appear.

**Comment by micc83** [comment]
Sorry but I've never tested the library with Icomoon so, I'm sorry, I can't help.
